### ISSUE TITLE
ESN ISAAP Code breaks items 

### ISSUE THREAD

**Issue by EvanSchallerer** [osu-cass/smarter-balanced-item-viewer#50]
Using ESN as an ISAAP code causes the error message: 
"Unable to load item. Please make sure you entered the correct bank and item numbers."

Happy case:
/item/187-2643

Bad case:
/item/187-2643?isaap=ESN

**Comment by Garrett-S** [comment]
This is caused by passing the ESN language code to an ELA item with no Spanish translation. The item renderer throws a null pointer exception because there is no Spanish translation.

The Sample Items Website was flipping which accessibility options are enabled/disabled when some options in a single select list were disabled.
Alex and I fixed the applicable accessibility options in the Sample Items website so it provides the correct accessibility options.

**Comment by alexlepinski** [comment]
Not an issue we will fix in Item Viewer Service but in IRiS
